### PR TITLE
Search preferences keyword handling fixes

### PR DESCRIPTION
**Pull request by wincak**
Fixes for issue #1061 (points 3 and 4) plus UI modification to show search engine keywords in the ReAdd menu.

### CODE REVIEW

**Comment by Emdek** [comment]
@wincak, could you please prepare variant without deduplication?
It makes review much harder than it should be. ;-)
It would be best to amend / replace existing commit, keeping current change in gist or somewhere for now.

**Comment by wincak** [comment]
@Emdek: done. There were some conflicts when I tried to merge this into current code, but it seemed just like formalities (brackets). And I will put the complete changes with deduplication into gist as soon as I find out how to properly do that :)

**Comment by Emdek** [comment]
@wincak, thanks for update and sorry for such long delay...
Now it's surely easier to review it. ;-)

At first glance it looks fine, with two exceptions:
 - initialization syntax was cleaned up recently (`const SearchEngineDefinition searchEngine = loadSearchEngine(&file, searchEnginesOrder.at(i), true);` -> `const SearchEngineDefinition searchEngine(loadSearchEngine(&file, searchEnginesOrder.at(i), true));` etc.),
 - change in `PreferencesSearchPageWidget::updateReaddSearchMenu()` is unrelated and should be pushed separately, but I need to think about it some more first.

**Comment by wincak** [comment]
No need to apologize, seems like my response isn't exactly fast either these days..
Anyway, I have rebased the branch, updated initialization syntax and removed the updateReaddSearchMenu() related change. However, a way of seeing saved search engines settings would be nice at least in some point in the future. Maybe in a more subtle way like a tooltip on mouse hover? Or opening "Edit search engine" dialog instead of directly readding back to the list?

**Comment by Emdek** [comment]
@wincak, thanks.
Perhaps we could go for something like this:

> Search Engine Name [keyword]

But I don't think that it is really that important, it is easy to assign keyword again.

**Comment by wincak** [comment]
@Emdek thank you for merging my changes!
And I guess you are right, it works fine like it is now.

**Pull request merged**
