### PR TITLE
Add StartPage search engine entry

### PR DESCRIPTION
**Pull request by welandtb**
Added an entry for StartPage by ixquick to the list of default search
engines.

Signed-off-by: Weland Treebark <weland@blinkenshell.org>

### CODE REVIEW

**Comment by welandtb** [comment]
This issue struck a quick sensible chord with me: https://github.com/Emdek/otter/issues/679 .

I often use startpage, too, since it tends to provide results that are more relevant than DuckDuckGo's. No matter how much I want to support DDG, I sometimes reach out to SP because the results aren't even close to what I need.

Startpage.com doesn't seem to provide an OpenSearch entry in any obvious place, but their instructions on how to add a StartPage entry to your browser were clear enough for me to be able to carve out a new entry based on DuckDuckGo's.

Oh... just in case, my sincerest apologies if this pull request isn't done properly! Back In My Day (TM) this was done by submitting patches to a mailing list and all this fork and pull request stuff is a wee bit weird...

**Comment by Emdek** [comment]
Nah, it's not bad. :-)

There are three very minor issues:
 - entries in *resources.qrc* should be ordered alphabetically (QtCreator always appends new stuff at end...),
 - I would change order to:
`duckduckgo,wikipedia,startpage,google,yahoo,bing,youtube`
 - please modify contents of Image tag in *startpage.xml* to make it a single line.

BTW, it's good idea to run `pngcrush` or similar on PNG file before encoding it as base64 (assuming that it wasn't done yet). :-)

Preferred approach is to do soft reset on branch and force push it after committing changes, no need to recreate pull request etc., just post comment when ready.

**Comment by welandtb** [comment]
Got it. I'll take care of these issues as soon as possible (most likely this evening when I get home) and get back to you. Having resources ordered alphabetically is a nitpick of mine as well, I have no idea how I didn't notice that :).

**Comment by Emdek** [comment]
OK. :-)

**Comment by welandtb** [comment]
Sorry it took me so long :). Let's see:

- I rearranged the entries in the resources file, they're in alphabetical order now.
- Changed order in options.ini as you mentioned
- Changed Image tag in startpage.xml to make it a single line (guess who isn't out of stone age and still wraps everything around at 78 columns :) )
- Ran the favicon through pngcrush, which reduced its size from 1.1K to 992 bytes.

Please let me know if there is anything else I should change!

**Comment by Emdek** [comment]
Nope, looks good, thanks. :-)

**Pull request merged**
