### PR TITLE
Add project URL to About dialog. (Fixes #1101)

### LINKED ISSUE #1101: URL in dialog About
URL to Otter Browser homepage is missing from dialog About.

### PR DESCRIPTION
**Pull request by elebow**
Quick fix for https://github.com/OtterBrowser/otter-browser/issues/1101.

### CODE REVIEW

**Comment by elebow** [comment]
Changed `'` to `\"` as I saw in IRC is preferred.

**Comment by Emdek** [comment]
@elebow, thanks, also I like that you managed to keep it as single commit. ;-)

**Comment by GreenLunar** [comment]
Thanks!

@elebow, I like your PNG avatar :)

**Comment by Frenzie** [comment]
@elebow Me too! I have a few stegosaurus figures in a box over at my parents' place somewhere. =P

**Comment by GreenLunar** [comment]
This URL is opened in default web browser.
This URL should be opened only with Otter Browser.

**Pull request merged**
