### PR TITLE
Do not display BookmarkPropertiesDialog when triggering BookmarkPageA…

### PR DESCRIPTION
**Pull request by fnkkio**
It doesn't make sense to be able to bookmark the about:start page.

### CODE REVIEW

**Comment by Emdek** [comment]
I think that it would better to simply replace that check by `Utils::isUrlEmpty(url)`.

**Comment by fnkkio** [comment]
@Emdek Updated

**Comment by Emdek** [comment]
@fnkkio, there is no need to keep `url.isEmpty()`, it's the first thing checked by `isUrlEmpty()`.

**Comment by fnkkio** [comment]
@Emdek My bad.

**Pull request merged**
