### PR TITLE
Switch images loading policy with Shift+I

### PR DESCRIPTION
**Pull request by paradogz**
A missing feature from Opera

### CODE REVIEW

**Comment by Emdek** [comment]
@paradogz, there is much simpler way to do that, using extended capabilities of `SetOptionAction` (using different shortcut since Ctrl+I is already in use...):
```
{
	"action": "SetOption",
	"parameters": {
		"mode": "toggle",
		"option": "Permissions/EnableImages"
	},
	"shortcuts": [
		"Ctrl+M"
	]
},
```
The issue is, what shortcut it should be then? And do we really need one by default?
Perhaps it would be better to collect such configuration examples for power users or even prepare prepare separate keyboard profile that prefers classic shortcuts.

**Comment by Frenzie** [comment]
I probably haven't used it in years. I used it quite a bit in the dial-up era, but unlike scripts it doesn't tend to affect loading times too much these days. Maybe for data saving while using mobile tethering?

**Comment by paradogz** [comment]
@Emdek
I tried your example, but it does not seem to work. Even though the new action appears in keyboard shortcuts window, Ctrl+M does nothing (F12-Images stays in the same state). I could not find any other examples of SetOption action, is it fully supported at the moment?

Can't we just use Shift+I, same as in Opera? (http://help.opera.com/Linux/12.00/en/keyboard.html#single-key). It could be a separate profile for classic shortcuts as well.
@Frenzie
Yes, it is useful for data saving.

**Comment by Emdek** [comment]
@paradogz, it definitely works, but it was possible that you hit recently fixed issue where some action shortcuts could end up duplicated when there were definitions for these actions with parameters too.
Plus of course testing required adding that snippet to active profile. ;-)

One issue still remains, should we have default shortcut for such action? What should it be?
Perhaps only as part of some sort of alternative keyboard configuration, even more compatible with classic Opera, where it prefers such less often used actions over more common ones.

**Comment by paradogz** [comment]
All right, SetOptionAction seems to work in the latest version. But images are not loaded anymore when "Enabled" is toggled! Do you know what could be the reason?
Another question: is it possible to change the toggling sequence? Now it is Disabled -> Enabled -> Cached only, would be more convenient to have Disabled -> Cached only -> Enabled like in Opera.

In my opinion, this shortcut could be part of "Enable single key shortcuts" (intended for advanced users). But it could be a separate keyboard configuration as well.

**Pull request closed without merging**
