### PR TITLE
Debian packaging of the 1.0.03 version

### PR DESCRIPTION
**Pull request by mquinson**
I wanted to test otter on my machine. Since I'm a big fan of Debian, I prefer to do so through the package, so I first refreshed it. I hope you like it.

### CODE REVIEW

**Comment by alexmyczko** [comment]
so have i: http://sid.ethz.ch/debian/otter-browser/

**Comment by mquinson** [comment]
Damn, I'm emptty on that system, but I didnt see the notification, sorry.
I'm OK with being a co-maintainer on need, yes.

**Comment by mquinson** [comment]
Closing this PR since my code is much worse than the one provided by @alexmyczko

**Comment by alexmyczko** [comment]
@mquinson well there's still this I don't know what to do about: E: otter-browser source: license-problem-convert-utf-code [3rdparty/breakpad/src/common/convert_UTF.c]

**Comment by mquinson** [comment]
@alexmyczko ouch, this is a big one, indeed. Would it be possible to patch the otter code to not use breakpad? My first guess is that it would be easier than patching breakpad to use libicu but I may be wrong. In particular, it seems that the chromium package contains a breakpad version without the `convert_UTF.c` file. Understanding how it's working in chromium could be a big hint.

**Pull request closed without merging**
