### PR TITLE
Add icons for Linux/BSD distributions to README.md

### PR DESCRIPTION
**Pull request by mkljczk**

### CODE REVIEW

**Comment by resetnow** [comment]
Why not add all those links directly instead of using your own site?

**Comment by m4sk1n** [comment]
@resetnow, just because it wouldn't surprise me if I'll have to change something and then I can just do it without unneeded commit.

**Comment by beastie1** [comment]
Perhaps you could add [Puffy](https://www.openbsd.org/art4.html) since OpenBSD has a [port](http://openports.se/www/otter-browser) of Otter Browser.

**Comment by m4sk1n** [comment]
@beastie1 find me a good looking Puffy icon (in 32x32) :D

**Pull request closed without merging**
