### PR TITLE
Some Debian changes

### PR DESCRIPTION
**Pull request by mati75**
I started prepare official Debian package. Debian check system lintian return warnings with this two things.

### CODE REVIEW

**Comment by Frenzie** [comment]
`Allow GERUND` would be better in every case. Allow loading plugins on demand, allow entering full screen, etc.

Lintian complains about keywords? Must be new. Anyway, neat! =)

**Comment by mati75** [comment]
Here is: https://lintian.debian.org/tags/desktop-entry-lacks-keywords-entry.html info about this

**Comment by Emdek** [comment]
@mati75, sorry for delayed reply, when I saw length of diff it landed on my "for later" list and it took longer than expect to process it. :-/

"Allow one" doesn't look good to me, we could switch to form similar to that used by classic Opera, for example: "Allow closing of windows" etc. or something else if needed.
I wonder why nobody was complaining about "occured" yet. :-D

BTW, you shouldn't touch .ts files, these are generated automatically from sources.

Are there any docs on topic of Keywords?
Firefox uses just: "web;browser;internet;".

**Comment by Frenzie** [comment]
Like I said, `Allow GERUND` (closing etc. are gerunds) is better in every case. I swear it on my English degree. =P

**Comment by alexmyczko** [comment]
what is the state of official debian packaging?

**Comment by mati75** [comment]
I abandoned this idea. A few years ago it didn't make sense as there were a lot of replacements in Debian repository. Currently, I do not have time to develop this idea.

**Comment by alexmyczko** [comment]
if anyone wants to pick this up: http://sid.ethz.ch/debian/otter-browser/

**Pull request closed without merging**
